using System;
using System.Collections.Generic;
using System.Text;

namespace LD36.Models
{
    /// <summary>
    /// These are the things the player needs to do during the operation period. Some
    /// are generated by the CEO during the budget phase (tasks). Others are generated during
    /// the operation period (tickets). User can assign these tasks to employees.
    /// </summary>
    class TodoList
    {
        public List<TodoItem> _todoList = new List<TodoItem>();

        public IEnumerable<TodoItem> Items => _todoList;

        public void AddTodoItem(TodoItem todoItem)
        {
            _todoList.Add(todoItem);
        }
    }
}
